version: '3.8'
# Database username and password are defined in Event-Countdown-Backend
services:
  db:
    image: db
    container_name: db_container
    env_file:
      - ./Event-Countdown-Backend/variables.env
    build:
      context: ./Event-Countdown-Backend
      dockerfile: Dockerfile.db

  backend:
    image: backend
    container_name: backend_container
    env_file:
      - ./Event-Countdown-Backend/variables.env
    environment:
      - DATABASE_URL='postgresql://' + process.env.POSTGRES_USER + ':' + process.env.POSTGRES_PASSWORD + '@db:5432/event_countdown_db?sslmode=disable'
    build:
      context: ./Event-Countdown-Backend
      dockerfile: Dockerfile.backend
    depends_on:
      - db
    ports:
      - "8080:8080"

  frontend:
    image: frontend
    container_name: frontend_container
    build:
      context: ./Event-Countdown-Ionic
      dockerfile: Dockerfile.frontend
    depends_on:
      - backend
    ports:
      - "80:4200"